const a = {
  AAPL: "Apple Inc.",
  TSLA: "Tesla, Inc.",
  MCD: "McDonald's Corporation",
  VZ: "Verizon Communications Inc.",
  BA: "The Boeing Company",
  NKE: "NIKE, Inc.",
  ALB: "Albemarle Corporation",
  AOS: "A. O. Smith Corporation",
  APPS: "Digital Turbine, Inc.",
  AQB: "AquaBounty Technologies, Inc.",
  ASPN: "Aspen Aerogels, Inc.",
  ATHM: "Autohome Inc.",
  BCYC: "Bicycle Therapeutics plc",
  BGNE: "BeiGene, Ltd.",
  CAT: "Caterpillar Inc.",
  CC: "The Chemours Company",
  CLAR: "Clarus Corporation",
  CMBM: "Cambium Networks Corporation",
  CMT: "Core Molding Technologies, Inc.",
  CRDF: "Cardiff Oncology, Inc.",
  CYD: "China Yuchai International Limited",
  DE: "Deere & Company",
  DKNG: "DraftKings Inc.",
  EMN: "Eastman Chemical Company",
  FBIO: "Fortress Biotech, Inc.",
  FBRX: "Forte Biosciences, Inc.",
  FCX: "Freeport-McMoRan Inc.",
  FLXS: "Flexsteel Industries, Inc.",
  FMC: "FMC Corporation",
  GME: "GameStop Corp.",
  GRVY: "Gravity Co., Ltd.",
  HAIN: "The Hain Celestial Group, Inc.",
  HBM: "Hudbay Minerals Inc.",
  HIBB: "Hibbett, Inc.",
  IEX: "IDEX Corporation",
  IOR: "Income Opportunity Realty Investors, Inc.",
  GOOGL: "Alphabet Inc.",
  MPX: "Marine Products Corporation",
  NSTG: "NanoString Technologies, Inc.",
  NVCR: "NovoCure Limited",
  NVO: "Novo Nordisk A/S",
  OESX: "Orion Energy Systems, Inc.",
  PENN: "PENN Entertainment, Inc.",
  PLL: "Piedmont Lithium Inc.",
  RDY: "Dr. Reddy's Laboratories Limited",
  REKR: "Rekor Systems, Inc.",
  SQM: "Sociedad Química y Minera de Chile S.A.",
  TCON: "TRACON Pharmaceuticals, Inc.",
  TGB: "Taseko Mines Limited",
  UEC: "Uranium Energy Corp.",
  VCEL: "Vericel Corporation",
  VOXX: "VOXX International Corporation",
  WKHS: "Workhorse Group Inc.",
  XNCR: "Xencor, Inc.",
};

console.log(JSON.stringify(a));
